In [1]:
import pandas as pd
import numpy as np

In [2]:
ds = pd.read_csv("Housing.csv")
x = ds.iloc[:,1:-1].values
y = ds.iloc[:,-1].values

In [3]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,5] = le1.fit_transform(x[:,5])

In [4]:
le2 = LabelEncoder()
x[:,6] = le2.fit_transform(x[:,6])

In [5]:
le3 = LabelEncoder()
x[:,7] = le3.fit_transform(x[:,7])

In [6]:
le4 = LabelEncoder()
x[:,8] = le4.fit_transform(x[:,8])

In [7]:
le5 = LabelEncoder()
x[:,9] = le5.fit_transform(x[:,9])

In [8]:
print(x)

[[42000 5850 3 ... 0 0 1]
 [38500 4000 2 ... 0 0 0]
 [49500 3060 3 ... 0 0 0]
 ...
 [103000 6000 3 ... 0 1 1]
 [105000 6000 3 ... 0 1 1]
 [105000 6000 3 ... 0 1 1]]


In [9]:
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.25, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,0:2] = sc.fit_transform(x_train[:,0:2])
x_test[:,0:2] = sc.transform(x_test[:,0:2])

In [12]:
print(x_test)

[[-0.3691482724959258 0.6555107224580111 3 ... 0 1 1]
 [2.4146131506259256 1.2729512090878141 3 ... 0 0 0]
 [-0.4842104113182956 1.483442284075247 3 ... 0 0 2]
 ...
 [0.7443562967528148 0.718658044954241 4 ... 1 0 1]
 [-0.5547323673707159 -0.8880904941164964 3 ... 0 0 0]
 [0.8185899347027308 0.7116416757879932 3 ... 0 1 0]]


In [13]:
print(x_train)

[[-1.2599519278949183 -0.8880904941164964 2 ... 0 0 0]
 [0.07625355520357044 -0.42968770858830935 3 ... 0 0 0]
 [0.29895446905331857 1.6097369290677068 3 ... 0 1 2]
 ...
 [0.8000315252152518 0.19710793692982403 3 ... 0 1 1]
 [1.4866926762519752 0.7116416757879932 3 ... 0 1 3]
 [-0.9259005571202961 -0.7477631107915412 3 ... 0 0 1]]


In [14]:
from sklearn.tree import DecisionTreeClassifier
cl = DecisionTreeClassifier(criterion='entropy', random_state=0)
cl.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [15]:
y_pred = cl.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[78 24]
 [14 21]]


0.7226277372262774