In [1]:
import pandas as pd
import numpy as np

In [2]:
ds = pd.read_csv("Housing.csv")
x = ds.iloc[:,:-1].values
y = ds.iloc[:,-1].values

In [3]:
print(x)

[[1 42000 5850 ... 'no' 'no' 1]
 [2 38500 4000 ... 'no' 'no' 0]
 [3 49500 3060 ... 'no' 'no' 0]
 ...
 [544 103000 6000 ... 'no' 'yes' 1]
 [545 105000 6000 ... 'no' 'yes' 1]
 [546 105000 6000 ... 'no' 'yes' 1]]


In [4]:
print(y)

['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 

Label encoding the other category 

In [5]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,6] = le1.fit_transform(x[:,6])

In [6]:
from sklearn.preprocessing import LabelEncoder
le2 = LabelEncoder()
x[:,7] = le2.fit_transform(x[:,7])

In [7]:
from sklearn.preprocessing import LabelEncoder
le3 = LabelEncoder()
x[:,8] = le3.fit_transform(x[:,8])

In [8]:
from sklearn.preprocessing import LabelEncoder
le4 = LabelEncoder()
x[:,9] = le4.fit_transform(x[:,9])

In [9]:
from sklearn.preprocessing import LabelEncoder
le5 = LabelEncoder()
x[:,10] = le5.fit_transform(x[:,10])

In [10]:
print(x)

[[1 42000 5850 ... 0 0 1]
 [2 38500 4000 ... 0 0 0]
 [3 49500 3060 ... 0 0 0]
 ...
 [544 103000 6000 ... 0 1 1]
 [545 105000 6000 ... 0 1 1]
 [546 105000 6000 ... 0 1 1]]


Categorical Encoding to dependent variable 

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 0 0 0 0 0 0 

Spliting the dataset into training set and test set

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.25, random_state=0)

Feature Scaling 

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,1:3] = sc.fit_transform(x_train[:,1:3])
x_test[:,1:3] = sc.transform(x_test[:,1:3])

In [15]:
print(x_train)

[[195 -1.2599519278949183 -0.8880904941164964 ... 0 0 0]
 [8 0.07625355520357044 -0.42968770858830935 ... 0 0 0]
 [508 0.29895446905331857 1.6097369290677068 ... 0 1 2]
 ...
 [10 0.8000315252152518 0.19710793692982403 ... 0 1 1]
 [360 1.4866926762519752 0.7116416757879932 ... 0 1 3]
 [193 -0.9259005571202961 -0.7477631107915412 ... 0 0 1]]


In [16]:
print(x_test)

[[86 -0.3691482724959258 0.6555107224580111 ... 0 1 1]
 [437 2.4146131506259256 1.2729512090878141 ... 0 0 0]
 [97 -0.4842104113182956 1.483442284075247 ... 0 0 2]
 ...
 [232 0.7443562967528148 0.718658044954241 ... 1 0 1]
 [214 -0.5547323673707159 -0.8880904941164964 ... 0 0 0]
 [409 0.8185899347027308 0.7116416757879932 ... 0 1 0]]


training the model on training set

In [17]:
from sklearn.svm import SVC
cl = SVC(kernel='linear', random_state=0)
cl.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

predticting the result on test set

In [18]:
y_pred = cl.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]]


Evaluating the model

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[92 10]
 [ 8 27]]


0.8686131386861314